### ISSUE TITLE
InputTimePicker/InputTimeZone unstable test

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10227]
### Priority impact

p - high

### Test type

unstable

### Which Component(s)

`input-time-picker`, `input-time-zone`

### Unstable Tests

openClose("calcite-input-time-picker", { initialToggleValue: true });

### Test error, if applicable

Summary of all failing tests
@esri/calcite-components:test: FAIL src/components/input-time-picker/input-time-picker.e2e.ts (51.699 s)
@esri/calcite-components:test:   ● calcite-input-time-picker › openClose › initially open › emits on initialization with animations enabled
@esri/calcite-components:test: 
@esri/calcite-components:test:     expect(received).toBeGreaterThan(expected)
@esri/calcite-components:test: 
@esri/calcite-components:test:     Expected: > 100
@esri/calcite-components:test:     Received:   1
@esri/calcite-components:test: 
@esri/calcite-components:test:       205 |     const matcherName = animationsEnabled ? "toBeGreaterThan" : ("toBeLessThanOrEqual" as const);
@esri/calcite-components:test:       206 |
@esri/calcite-components:test:     > 207 |     expect(delayBetweenBeforeOpenAndOpen)[matcherName](delayDeltaThreshold);
@esri/calcite-components:test:           |                                                       ^
@esri/calcite-components:test:       208 |     expect(delayBetweenBeforeCloseAndClose)[matcherName](delayDeltaThreshold);
@esri/calcite-components:test:       209 |   }
@esri/calcite-components:test:       210 |
@esri/calcite-components:test: 
@esri/calcite-components:test:       at testOpenCloseEvents (src/tests/commonTests/openClose.ts:207:55)
@esri/calcite-components:test:       at Object.<anonymous> (src/tests/commonTests/openClose.ts:218:7)
@esri/calcite-components:test: 
@esri/calcite-components:test:

Same test failure for `input-time-zone`.

### PR skipped, if applicable

#10226, #10228

**Comment by jcfranco** [comment]
Noticed a similar failure locally with https://github.com/Esri/calcite-design-system/pull/10228. Will update the issue title/description to investigate both under this issue.

**Comment by jcfranco** [comment]
#10228 addressed the `input-time-zone` failure. Will look into the `input-time-picker` one.

**Comment by jcfranco** [comment]
#10310 might help here.

**Comment by geospatialem** [comment]
Spike needed to determine if the migration to Lit mitigates the failure.

**Comment by isaacbraun** [comment]
Verified on `dev` branch
