### ISSUE TITLE
Follow up on remaining Lumina migration notes

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#10731]
### Description

In addition to the migration notes added by #10310, the following should be addressed as well:

* refactor `filter#filter()` to use the debounced function (see ad054fd07e88b9cb304f02b7ec2006a146e10d08)
* revisit internal event emitting flag used in `list` (see ad054fd07e88b9cb304f02b7ec2006a146e10d08).
* ✅ ensure all open comboboxes are rendered in the snapshot ([Combobox: With Description Short Label And Content End Slot](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=6736c1960aca284626b19095)) – https://github.com/Esri/calcite-design-system/pull/10952
* ✅ fix GH pages content – https://github.com/Esri/calcite-design-system/pull/10807
* ✅ simplify config (see https://github.com/Esri/calcite-design-system/pull/10482/files/57fefcd2747528235d727a17fd947f0c4b4f6a96..04af92c28583f05b22db71f111717bf68e24afb6#r1844236385) - https://github.com/Esri/calcite-design-system/pull/11266

#### Stabilize

☑️ – no longer shows up
```
@esri/calcite-components:test:  FAIL  src/components/combobox/combobox.e2e.ts > calcite-combobox > reflects > %p scale
@esri/calcite-components:test: Error: vitest-fail-on-console > Expected test not to call console.error().
@esri/calcite-components:test:     If the error is expected, test for it explicitly by mocking it out using: 
@esri/calcite-components:test:     vi.spyOn(console, 'error').mockImplementation(() => {}) 
@esri/calcite-components:test:     and test that the warning occurs.
@esri/calcite-components:test: 
@esri/calcite-components:test: "chevronDown16" is not a valid calcite-ui-icon name 
@esri/calcite-components:test: Stack:
@esri/calcite-components:test:   http://localhost:5173/src/components/icon/utils.ts:23:14
@esri/calcite-components:test: 
@esri/calcite-components:test:     at Console.l [as error] (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/vitest-fail-on-console/src/index.ts:90:31)
@esri/calcite-components:test:     at ae (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/@arcgis/lumina-compiler/dist/puppeteerTesting/index.js:2:1926)
@esri/calcite-components:test:  ❯ Console.l [as error] ../../node_modules/vitest-fail-on-console/src/index.ts:90
```

✅ – https://github.com/Esri/calcite-design-system/pull/10818
```
@esri/calcite-components:test: 
@esri/calcite-components:test:  FAIL  src/components/segmented-control/segmented-control.e2e.ts > calcite-segmented-control > when multiple items are checked, last one wins
@esri/calcite-components:test: AssertionError: expected '1' to be '3' // Object.is equality
@esri/calcite-components:test: 
@esri/calcite-components:test: Expected: "3"
@esri/calcite-components:test: Received: "1"
```

##### Documentation Updates  
- Add docs package export (#11221)  
- Use updated translation bundle paths to generate `translations.json` (#11219)  

##### UI & Behavior Fixes  
- Avoid showing scroller when `max-items` equals items in dropdown (#11480)  
- Fix `has-children` logic in tree (#11347)  
- Keep initial focus on newly selected item in stepper-item (#11482)  
- Fix error in color-picker caused by initial value with a different format (#11351)  
- Improve prop update times in combobox (#11383)  
- Make `readOnly` prop writable in text-area (#11218)  
- Fix sporadic change event emitted on initialization in combobox (#10952)  
- Update internal state after custom value is added in combobox (#11405)  
- Drop relative-positioning in popover & tooltip to reduce clipping risk (#11373)  
- Toggle focus-trap on DOM connect/disconnect in dialog (#11429)  
- Fix rounded corners in sheet when `displayMode="float"` (#11086)  
- Stretch slotted actions only in accordion-item (#11082)  
- Fix toggle logic in action-menu when reconnected (#11139)  
- Fix selection indicator placement in RTL for list-item (#11288)  
- Ensure change & select events are emitted after state updates in list & list-item (#11079)  
- Restore deactivating focus traps on outside click in dialog, modal, popover & sheet (#11058)  
- Prevent `beforeClose` from being invoked during initialization in dialog & panel (#11038)  
- Disable sort-handle when no move-to items are present and item count is one (#11073)  
- Avoid using refs that have been nulled in input-date-picker, modal & tile-select (#11090)  
- Fix year-select width logic in date-picker (#11071)  
- Skip ref setup logic on component removal in popover & tooltip (#11132)  
- Fix initial item selection delay in combobox & input-time-zone (#11326)  

##### Performance & Core Fixes  
- Fix initialization performance regression in combobox (#11265)  
- Floating UI elements set `max-content` for `inline-size` (#11095)  
- Prevent transpilation issues by using `this` to reference static props (#11088)  
- Use `inert` on host elements instead of `aria-hidden` when hidden (#11056)  

### Proposed Advantages

Cleaner, simpler code.

### Which Component

N/A

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

**Comment by geospatialem** [comment]
Similar to the `segmented-control` timings, there may be some similar behavior occurring with the `list` component. A few notes below (also in our internal _migration notes and feedback_ issue) for consideration:  
- `list`'s `calciteListChange` event payload for it's `selectedItems` provides two values (old and new) when the `selectionMode` is in `"single"` or `"single-persist"`: https://codepen.io/geospatialem/pen/PwYPgrO
- `list`'s initial rendering doesn't provide the `list-item`'s node (it isn't ready)

**Comment by ellenupp** [comment]
`dialog` is raising a close event while initializing-

When creating a dialog with `open`, after its first willUpdate, `open` is true but `opened` is false. When it goes to render its panel it sets the panel’s `closed` to !opened. The panel has the default closed=false, so in its willUpdate it calls `close()` since the dialog set closed=true. This is a problem because we use `beforeClose` to dismiss the panel, removing it from the dom, so the open dialog never renders.

[Repro codepen](https://codepen.io/ellupp/pen/azoNzoK?editors=1010)

cc @driskull

**Comment by geospatialem** [comment]
Closing out the above, marked as verified. 🏆 

cc @jcfranco
