### ISSUE TITLE
Support ESLint's new flat config

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#11161]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

This will help us integrate better with ESLint v9 since flat config is now the default (see https://eslint.org/blog/2024/04/eslint-v9.0.0-released/#flat-config-is-now-the-default-and-has-some-changes).

### Acceptance Criteria

Flat configs are supported and used by the `calcite-components` package.

### Relevant Info

https://github.com/Esri/calcite-design-system/pull/10938/ enabled recommended rules to avoid using the current config, which produced the following error:

```bash
Oops! Something went wrong! :(

ESLint: 9.17.0

TypeError: Key "rules": Key "@esri/calcite-components/no-dynamic-createelement": Could not find plugin "@esri/calcite-components".
    at throwRuleNotFoundError (/example/path/to/project/node_modules/eslint/lib/config/rule-validator.js:66:11)
    at RuleValidator.validate (/example/path/to/project/node_modules/eslint/lib/config/rule-validator.js:147:17)
    at new Config (/example/path/to/project/node_modules/eslint/lib/config/config.js:228:27)
    at [finalizeConfig] (/example/path/to/project/node_modules/eslint/lib/config/flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (/example/path/to/project/node_modules/@eslint/config-array/dist/cjs/index.cjs:1178:55)
    at FlatConfigArray.getConfig (/example/path/to/project/node_modules/@eslint/config-array/dist/cjs/index.cjs:1196:15)
    at entryFilter (/example/path/to/project/node_modules/eslint/lib/eslint/eslint-helpers.js:282:40)
    at async NodeHfs.<anonymous> (file:///example/path/to/project/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.<anonymous> (file:///example/path/to/project/node_modules/@humanfs/core/src/hfs.js:604:6)
    at async NodeHfs.<anonymous> (file:///example/path/to/project/node_modules/@humanfs/core/src/hfs.js:604:6)
```

cc @benelan 

### Which Component

N/A

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [X] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/10938.
