### ISSUE TITLE
Unstable tests: Action Bar, Filter, Input Text, Input Number, Modal, Radio Button

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#5377]
### Test type

unstable tests

### Which Component(s)

 action-bar, input-text, input-number, modal, radio-button

### Unstable Tests

- ~`calcite-action-bar › overflow actions › should slot 'menu-actions' on resize of component`~

- ~`calcite-input-number › increment/decrement functionality › should emit an event on an interval when up/down buttons are down and stop on mouseup/mouseleave`~ https://github.com/Esri/calcite-design-system/issues/9784

- ~`calcite-input-text › emits events when value is modified`~

- ~`calcite-radio-button › appropriately triggers the custom internal focus and blur events with keyboard`~

- ~`calcite-modal accessibility checks › setFocus › can focus close button directly`~ https://github.com/Esri/calcite-design-system/pull/6147

### Test error, if applicable

```
FAIL src/components/action-bar/action-bar.e2e.ts (35.548 s)
  ● calcite-action-bar › overflow actions › should slot 'menu-actions' on resize of component
    expect(received).toHaveLength(expected)
    Expected length: 7
    Received length: 0
    Received array:  []
      365 |
      366 |       expect(await page.findAll(dynamicGroupActionsSelector)).toHaveLength(8);
    > 367 |       expect(await page.findAll(slottedActionsSelector)).toHaveLength(7);
          |                                                          ^
      368 |
      369 |       await page.$eval("calcite-action-bar", (element: HTMLCalciteActionBarElement) => {
      370 |         element.style.height = "550px";
      at Object.<anonymous> (src/components/action-bar/action-bar.e2e.ts:367:58)
          at runMicrotasks (<anonymous>)
```

```
FAIL src/components/input-number/input-number.e2e.ts (631.399 s)
  ● calcite-input-number › increment/decrement functionality › should emit an event on an interval when up/down buttons are down and stop on mouseup/mouseleave
    expect(received).toBe(expected) // Object.is equality
    Expected: "3"
    Received: "4"
      476 |
      477 |       totalNudgesUp = calciteInputNumberInput.length;
    > 478 |       expect(await input.getProperty("value")).toBe(`${totalNudgesUp}`);
          |                                                ^
      479 |
      480 |       // assert changes no longer emitted after moving away from stepper
      481 |       await page.waitForTimeout(delayFor2UpdatesInMs);
      at Object.<anonymous> (src/components/input-number/input-number.e2e.ts:478:48)
          at runMicrotasks (<anonymous>)
```

```
FAIL src/components/input-text/input-text.e2e.ts (46.754 s)
  ● calcite-input-text › emits events when value is modified
    expected event "calciteInputTextChange" to have been called 2 times, but was called 1 time
      134 |     await page.keyboard.press("Tab");
      135 |     expect(calciteInputTextInput).toHaveReceivedEventTimes(10);
    > 136 |     expect(calciteInputTextChange).toHaveReceivedEventTimes(2);
          |                                    ^
      137 |     expect(await element.getProperty("value")).toBe(`${inputFirstPart}${textSecondPart}`);
      138 |
      139 |     await element.callMethod("setFocus");
      at Object.<anonymous> (src/components/input-text/input-text.e2e.ts:136:36)
          at runMicrotasks (<anonymous>)
```

```
 FAIL src/components/modal/modal.e2e.ts (40.465 s) 
3477 ● calcite-modal accessibility checks › setFocus › can focus close button directly 
3478 
3479 Evaluation failed: TypeError: Cannot read property 'matches' of null 
3480 
3481 at __puppeteer_evaluation_script__:1:58 
3482 at ExecutionContext._evaluateInternal (node_modules/puppeteer/src/common/ExecutionContext.ts:273:13) 
3483 at runMicrotasks (<anonymous>) 
3484 at ExecutionContext.evaluate (node_modules/puppeteer/src/common/ExecutionContext.ts:140:12) 
3485 at ElementHandle.evaluate (node_modules/puppeteer/src/common/JSHandle.ts:161:12) 
3486 at ElementHandle.$eval (node_modules/puppeteer/src/common/JSHandle.ts:834:20) 
3487 at focusable (src/tests/commonTests.ts:216:7)
```

```
FAIL src/components/radio-button/radio-button.e2e.ts (46.704 s)
  ● calcite-radio-button › appropriately triggers the custom internal focus and blur events with keyboard
    expected event "calciteInternalRadioButtonFocus" to have been called 1 times, but was called 0 time
      291 |     await page.keyboard.press("Tab");
      292 |
    > 293 |     expect(focusEvent).toHaveReceivedEventTimes(1);
          |                        ^
      294 |     expect(blurEvent).toHaveReceivedEventTimes(0);
      295 |
      296 |     await page.keyboard.press("ArrowRight");
      at Object.<anonymous> (src/components/radio-button/radio-button.e2e.ts:293:24)
          at runMicrotasks (<anonymous>)
```

### PR skipped, if applicable

#5376

**Comment by jcfranco** [comment]
The remaining unstable tests from this issue were addressed in https://github.com/Esri/calcite-design-system/pull/12355. Closing!
