### ISSUE TITLE
Unstable test: dropdown

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#5492]
### Test type

e2e

### Which Component(s)

dropdown

### Unstable Tests

dropdown should not overflow when wrapped inside a tab

### Test error, if applicable

FAIL src/components/dropdown/dropdown.e2e.ts (70.409 s)
  ● calcite-dropdown › dropdown should not overflow when wrapped inside a tab #3007

    Node is either not visible or not an HTMLElement

      1087 |     const button = await page.find("calcite-button");
      1088 |
    > 1089 |     await button.click();
           |     ^
      1090 |     await page.waitForChanges();
      1091 |
      1092 |     expect(

      at ElementHandle._clickablePoint (node_modules/puppeteer/src/common/JSHandle.ts:424:13)
          at runMicrotasks (<anonymous>)
      at ElementHandle.click (node_modules/puppeteer/src/common/JSHandle.ts:496:22)
      at E2EElement.click (node_modules/@stencil/core/testing/index.js:3335:3)
      at Object.<anonymous> (src/components/dropdown/dropdown.e2e.ts:1089:5)

### PR skipped, if applicable

#5491

**Comment by geospatialem** [comment]
Verified on the `dev` branch
