### ISSUE TITLE
Unstable test: modal

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#5494]
### Test type

e2e

### Which Component(s)

modal

### Unstable Tests

opening and closing behavior › opens and closes

### Test error, if applicable

FAIL src/components/modal/modal.e2e.ts (51.313 s)
  ● opening and closing behavior › opens and closes

    Evaluation failed: Error: waitForEvent() timeout, eventName: calciteModalBeforeClose

      at __puppeteer_evaluation_script__:3:6
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
          at runMicrotasks (<anonymous>)
      at ExecutionContext.evaluate (node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
      at waitForEvent (node_modules/@stencil/core/testing/index.js:795:55)
      at Object.<anonymous> (src/components/modal/modal.e2e.ts:118:5)

### PR skipped, if applicable

#5491

**Comment by jcfranco** [comment]
This is no longer valid as the test was replaced by https://github.com/Esri/calcite-design-system/pull/8392. Closing!
