### ISSUE TITLE
Look into stripping out testing `data-` attributes from production code.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#6760]
**monday.com sync:** #18048707802

### Background

https://github.com/Esri/calcite-components/pull/6746#discussion_r1162056759

### Desired Outcome

Any data attributes or testing specific code is removed from the production code.

_May have some risk involved and it could impact current component functionality._ 🚧

**Comment by jcfranco** [comment]
I think I have something we could use for this: https://github.com/Esri/calcite-design-system/pull/8171.

**Comment by driskull** [comment]
We could convert all the `data-test` attributes to `id`. there aren't too many

<img width="372" alt="image" src="https://github.com/user-attachments/assets/01203712-23c9-48d3-a214-3514f8a2a258">

**Comment by jcfranco** [comment]
Based on https://github.com/vitejs/vite/discussions/10408, we might be able to handle this at the build level. https://github.com/jacobbogers/rollup-plugin-jsx-remove-attributes looks promising, but we’ll need to wait until https://github.com/estools/escodegen/pull/465 lands and the plugin is updated to use it. Currently, it produces the following error:

```bash
x Build failed in 10.16s
error during build:
[vite-plugin-jsx-remove-attributes] this[type] is not a function
file: /.../calcite-design-system/packages/calcite-components/src/utils/number.js
at CodeGenerator.generateExpression (/.../calcite-design-system/node_modules/escodegen/escodegen.js:2517:28)
at /.../calcite-design-system/node_modules/escodegen/escodegen.js:1133:38
at withIndent (/.../calcite-design-system/node_modules/escodegen/escodegen.js:581:9)
at CodeGenerator.ClassBody (/.../calcite-design-system/node_modules/escodegen/escodegen.js:1128:13)
at CodeGenerator.generateStatement (/.../calcite-design-system/node_modules/escodegen/escodegen.js:2530:33)
at CodeGenerator.ClassDeclaration (/.../calcite-design-system/node_modules/escodegen/escodegen.js:1159:30)
at CodeGenerator.generateStatement (/.../calcite-design-system/node_modules/escodegen/escodegen.js:2530:33)
at CodeGenerator.ExportNamedDeclaration (/.../calcite-design-system/node_modules/escodegen/escodegen.js:1237:42)
at CodeGenerator.generateStatement (/.../calcite-design-system/node_modules/escodegen/escodegen.js:2530:33)
at CodeGenerator.Program (/.../calcite-design-system/node_modules/escodegen/escodegen.js:1718:43)
```

**Comment by jcfranco** [comment]
Update: It looks like `jacobbogers/rollup-plugin-jsx-remove-attributes` will be [getting an update soon](https://github.com/jacobbogers/rollup-plugin-jsx-remove-attributes/pull/4#issuecomment-2915550217), which should help us move forward with it as a viable solution.

**Comment by jcfranco** [comment]
The above PR has landed, but it's not working as expected:

1. when run before/after the `useLumina` plugin, it does remove attributes (no `JSXCallExpression` matches) and
2. when run with `enforce: "pre"`, it throws the following error:

    ```bash
    [vite-plugin-jsx-remove-attributes] Expected ',', got '{'
    file: /.../calcite-design-system/packages/calcite-components/src/components/fab/fab.tsx
    at getRollupError (file:///.../calcite-design-system/node_modules/rollup/dist/es/shared/parseAst.js:397:41)
    at convertProgram (file:///.../calcite-design-system/node_modules/rollup/dist/es/shared/parseAst.js:1085:26)
    at Object.parseAst [as parse] (file:///.../calcite-design-system/node_modules/rollup/dist/es/shared/parseAst.js:2070:87)
    at Object.transform (file:///.../calcite-design-system/node_modules/rollup-plugin-jsx-remove-attributes/dist/index.js:68:30)
    at Object.handler (file:///.../calcite-design-system/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:46508:15)
    at file:///.../calcite-design-system/node_modules/rollup/dist/es/shared/node-entry.js:22210:40
    ```

We'll need to look into this further.

**Comment by jacobbogers** [comment]
I am going to take a looksy, very curious why the plugin is reporting 

`[vite-plugin-jsx-remove-attributes] this[type] is not function`

**Comment by jcfranco** [comment]
@Esri/calcite-pes Moving this to the current milestone since a PR for it recently landed.

**Comment by DintaMel** [comment]
@jcfranco From the work on this issue, it seems like I need to do some basic regression testing, but the description says "May have some risk involved and it could impact current component functionality." Do you have any more info on why we think it might impact component functionality?

**Comment by jcfranco** [comment]
Not sure what the context of that warning is, but from the solution perspective, it should be pretty safe as it uses a build transformer that only targets `data-test` prefixed JSX attributes in production builds.

**Comment by DintaMel** [comment]
Regression tested multiple components to verify no change in functionality. Used version 5.0.0-next.12.
