### ISSUE TITLE
Unstable input tests

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7268]
### Test type

e2e test

### Which Component(s)

input-number, input-time-picker

### Test error, if applicable

```
@esri/calcite-components:test: Summary of all failing tests
@esri/calcite-components:test: FAIL src/components/input-time-picker/input-time-picker.e2e.ts (177.907 s)
@esri/calcite-components:test:   ● calcite-input-time-picker › correctly relocalizes the display value when the lang and numbering systems change
@esri/calcite-components:test: 
@esri/calcite-components:test:     expect(received).toBe(expected) // Object.is equality
@esri/calcite-components:test: 
@esri/calcite-components:test:     Expected: "02:30:25 م"
@esri/calcite-components:test:     Received: "14.30.25"
@esri/calcite-components:test: 
@esri/calcite-components:test:       642 |     await page.waitForChanges();
@esri/calcite-components:test:       643 |
@esri/calcite-components:test:     > 644 |     expect(await getInputValue(page)).toBe("02:30:25 م");
@esri/calcite-components:test:           |                                       ^
@esri/calcite-components:test:       645 |
@esri/calcite-components:test:       646 |     inputTimePicker.setProperty("numberingSystem", "arab");
@esri/calcite-components:test:       647 |     await page.waitForChanges();
@esri/calcite-components:test: 
@esri/calcite-components:test:       at Object.<anonymous> (src/components/input-time-picker/input-time-picker.e2e.ts:644:39)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test: 
@esri/calcite-components:test: FAIL src/components/input-number/input-number.e2e.ts (978.91 s)
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements numbers greater than MAX_SAFE_INTEGER
@esri/calcite-components:test: 
@esri/calcite-components:test:     expect(received).toBe(expected) // Object.is equality
@esri/calcite-components:test: 
@esri/calcite-components:test:     Expected: "100000000000000000000000000000000000000000000000009"
@esri/calcite-components:test:     Received: "100000000000000000000000000000000000000000000000009.4"
@esri/calcite-components:test: 
@esri/calcite-components:test:       231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:     > 233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:           |                                                  ^
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test:       235 |
@esri/calcite-components:test:       236 |     it("correctly increments/decrements exponential notation numbers without losing precision", async () => {
@esri/calcite-components:test: 
@esri/calcite-components:test:       at Object.<anonymous> (src/components/input-number/input-number.e2e.ts:233:50)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements numbers greater than MAX_SAFE_INTEGER
@esri/calcite-components:test: 
@esri/calcite-components:test:     TypeError: Cannot read properties of null (reading 'waitForChanges')
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:52)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     Protocol error (Input.dispatchMouseEvent): Target closed.
@esri/calcite-components:test: 
@esri/calcite-components:test:       229 |       element.setProperty("step", 0.1);
@esri/calcite-components:test:       230 |       await page.waitForChanges();
@esri/calcite-components:test:     > 231 |       Array.from({ length: 10 }, async () => await numberHorizontalItemDown.click());
@esri/calcite-components:test:           |                                              ^
@esri/calcite-components:test:       232 |       await page.waitForChanges();
@esri/calcite-components:test:       233 |       expect(await element.getProperty("value")).toBe("100000000000000000000000000000000000000000000000009");
@esri/calcite-components:test:       234 |     });
@esri/calcite-components:test: 
@esri/calcite-components:test:       at ../../node_modules/puppeteer/src/common/Connection.ts:291:57
@esri/calcite-components:test:       at CDPSession.send (../../node_modules/puppeteer/src/common/Connection.ts:290:12)
@esri/calcite-components:test:       at Mouse.up (../../node_modules/puppeteer/src/common/Input.ts:447:24)
@esri/calcite-components:test:       at Mouse.click (../../node_modules/puppeteer/src/common/Input.ts:419:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test:       at ElementHandle.click (../../node_modules/puppeteer/src/common/JSHandle.ts:497:5)
@esri/calcite-components:test:       at E2EElement.click (../../node_modules/@stencil/core/testing/index.js:3342:3)
@esri/calcite-components:test:       at src/components/input-number/input-number.e2e.ts:231:46
@esri/calcite-components:test: 
@esri/calcite-components:test:   ● calcite-input-number › increment/decrement functionality › correctly increments/decrements exponential notation numbers without losing precision
@esri/calcite-components:test: 
@esri/calcite-components:test:     The page was already closed
@esri/calcite-components:test: 
@esri/calcite-components:test:       235 |
@esri/calcite-components:test:       236 |     it("correctly increments/decrements exponential notation numbers without losing precision", async () => {
@esri/calcite-components:test:     > 237 |       await page.setContent(html`<calcite-input-number value="1.23e-60"></calcite-input-number>`);
@esri/calcite-components:test:           |                  ^
@esri/calcite-components:test:       238 |       const element = await page.find("calcite-input-number");
@esri/calcite-components:test:       239 |       const numberHorizontalItemDown = await page.find(
@esri/calcite-components:test:       240 |         "calcite-input-number >>> .number-button-item[data-adjustment='down']"
@esri/calcite-components:test: 
@esri/calcite-components:test:       at Page.r (../../node_modules/@stencil/core/testing/index.js:3925:11)
@esri/calcite-components:test:       at Object.<anonymous> (src/components/input-number/input-number.e2e.ts:237:18)
@esri/calcite-components:test:           at runMicrotasks (<anonymous>)
@esri/calcite-components:test: 
@esri/calcite-components:test: 
@esri/calcite-components:test: Test Suites: 2 failed, 1 skipped, 116 passed, 118 of 119 total
@esri/calcite-components:test: Tests:       3 failed, 38 skipped, 3437 passed, 3478 total
@esri/calcite-components:test: Snapshots:   0 total
@esri/calcite-components:test: Time:        1026.664 s
@esri/calcite-components:test: Ran all test suites.
@esri/calcite-components:test: 
@esri/calcite-components:test: npm ERR! Lifecycle script `test` failed with error: 
@esri/calcite-components:test: npm ERR! Error: command failed 
@esri/calcite-components:test: npm ERR!   in workspace: @esri/calcite-components@1.5.0-next.11 
@esri/calcite-components:test: npm ERR!   at location: /home/runner/work/calcite-design-system/calcite-design-system/packages/calcite-components 
@esri/calcite-components:test: ERROR: command finished with error: command (/home/runner/work/calcite-design-system/calcite-design-system/packages/calcite-components) npm run test exited (1)
```

### PR skipped, if applicable

#

**Comment by eriklharper** [comment]
Here's a comment thread with discussion or reference 
![image](https://github.com/Esri/calcite-design-system/assets/821864/e71d1331-7023-4ee9-becf-79eabe9bd63f)

**Comment by jcfranco** [comment]
`input-time-picker` test was restored in https://github.com/Esri/calcite-design-system/pull/9265/ and `input-number-tests` will be restored by https://github.com/Esri/calcite-design-system/issues/9784. Closing as a duplicate.
