### ISSUE TITLE
DragAndDrop utility fails when a spy is set in some tests

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7643]
**monday.com sync:** #18048490069

### Test type

Refactor

### Which Component(s)

DragAndDrop utility 

### Test error, if applicable

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/components/list/list.e2e.ts.

      at Object.get (../../node_modules/@stencil/core/testing/index.js:7:14)
      at Object.<anonymous> (../../node_modules/@stencil/core/testing/index.js:3772:79)

 RUNS  src/components/list/list.e2e.ts
/Users/dris0000/Sites/git/calcite-design-system/node_modules/@stencil/core/testing/index.js:3925
    throw new Error("The page was already closed");
          ^

Error: Caught error after test environment was torn down
```

### PR skipped, if applicable

#7614

### Additional Info

See https://github.com/Esri/calcite-design-system/pull/7614#discussion_r1309461010

**Comment by jcfranco** [comment]
Closing as this will no longer applicable once we fully migrate to browser mode in #11268. @Esri/calcite-pes
