### ISSUE TITLE
ArcGIS Experience Builder widget with Calcite component fails to run Jest tests

### ISSUE THREAD

**Issue by Matt-at-Hyland** [Esri/calcite-design-system#8827]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

While attempting to run the Jest tests after adding a CalciteAlert component to the sample Experience Builder widget the following error occurs:

Jest encountered an unexpected token
```
 FAIL  your-extensions/widgets/simple/tests/simple-widget.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\Temp\ExperenceBuilderCalciteJestIssue\client\node_modules\@esri\calcite-components-react\dist\index.js:45
        export * from "./components";
        ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { React, type AllWidgetProps } from 'jimu-core'
      2 | import { type IMConfig } from '../config'
    > 3 | import { CalciteAlert } from "@esri/calcite-components-react";
        | ^
      4 |
      5 | const Widget = (props: AllWidgetProps<IMConfig>) => {
      6 |   return (

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1496:14)
      at Object.<anonymous> (your-extensions/widgets/simple/src/runtime/widget.tsx:3:1)
      at Object.<anonymous> (your-extensions/widgets/simple/tests/simple-widget.test.tsx:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.381 s
```

### Expected Behavior

Jest tests can be run when Calcite components are being used

### Reproduction Sample

See repo steps

### Reproduction Steps

1. Set up Experience Builder from:
https://developers.arcgis.com/experience-builder/guide/install-guide/

2. Update to use the version 2.5.1 of the `@esri/calcite-components-react` dependency in the `client\package.json` file.

3. Follow instructions here to ensure Calcite components can be included in Jest tests:
https://developers.arcgis.com/calcite-design-system/resources/frameworks/#configuring-jest

4. Update the `client\your-extensions\widgets\simple\src\runtime\widget.tsx` file to include a CalciteAlert component:

```
import { React, type AllWidgetProps } from 'jimu-core'
import { type IMConfig } from '../config'
import { CalciteAlert } from "@esri/calcite-components-react";

const Widget = (props: AllWidgetProps<IMConfig>) => {
  return (
    <div className="widget-demo jimu-widget m-2">
      <CalciteAlert open icon={true} kind="warning" label="Test Calcite Alert" />
      <p>Simple Widget</p>
      <p>exampleConfigProperty: {props.config.exampleConfigProperty}</p>
    </div>
  )
}

export default Widget
```

5. Run the tests in the `client` folder via `npm test`

### Reproduction Version

2.5.1

### Priority impact

p1 - need for current milestone

### Impact

Blocking the ability to use Calcite components in Experience Builder UI.

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by jcfranco** [comment]
Thanks for submitting this. This may be a transformation issue on the Experience Builder test configuration side. Would you be able to provide a simplified repro case or share some additional info regarding your setup (e.g., Jest config)?

**Comment by Matt-at-Hyland** [comment]
Here is the jes.config.js from the /client folder
```
module.exports = {
  testEnvironment: 'jsdom',
  globals: {
    'ts-jest': {
      isolatedModules: true
    },
    // the default config is for AGOL app
    jimuConfig: {
      isBuilder: false,
      isSite: false,
      isInBuilder: false,
      isOutOfExb: false,
      rootPath: '/',
      appFolderName: '',
      baseUrl: '/',
      useStructuralUrl: true,
      isInPortal: false,
      mountPath: '/',
      hostEnv: 'prod',
      isDevEdition: false,
      arcgisJsApiUrl: '',
      buildNumber: '',
      exbVersion: '1.5.0'
    }
  },
  transform: {
    "^.+\\.tsx?$": "ts-jest",
    "\\.js$": "./jest-systemjs-transformer.js"
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@esri/arcgis-rest-types|@arcgis/charts-spec|@esri/calcite-components-react))'
  ],
  testEnvironmentOptions: {
    testURL: "http://localhost"
  },
  resolver: '<rootDir>/jimu-for-test/resolver-import.js',
  testRegex: "\\.(test|spec)\\.(tsx?)$",
  testPathIgnorePatterns: [
    "<rootDir>/node_modules/",
    "<rootDir>/woodpecker/",
    "<rootDir>/dist/",
    "<rootDir>/dist-tests/",
    "<rootDir>/dist-doc/",
    "<rootDir>/dist-report/",
    "<rootDir>/tests/testing-library-examples",
    "<rootDir>/__mocks__/",
    "<rootDir>/experience/",
    "<rootDir>/for-release/",
    "<rootDir>/pwa/",
    "<rootDir>/scripts/",
    "<rootDir>/test-loader/",
    "<rootDir>/tsconfig/",
    "<rootDir>/types/",
    "<rootDir>/webpack/"
  ],
  moduleFileExtensions: [
    "ts",
    "tsx",
    "js",
    "jsx"
  ],
  moduleNameMapper: {
    "^jimu-core$": "<rootDir>/dist/jimu-core/index.js",
    '^jimu-theme$': '<rootDir>/dist/jimu-theme/index.js',
    "^jimu-ui$": "<rootDir>/dist/jimu-ui/index.js",
    "^jimu-for-builder$": "<rootDir>/dist/jimu-for-builder/index.js",
    "^jimu-arcgis$": "<rootDir>/dist/jimu-arcgis/index.js",
    "^jimu-for-test$": "<rootDir>/jimu-for-test/index.tsx",

    "^jimu-ui/lib/icons/(.*)\\.svg": "<rootDir>/__mocks__/icon-mock.js",
    '^jimu-icons/svg/(.*)\\.svg': '<rootDir>/__mocks__/icon-mock.js',

    "^jimu-core/(.*)": "<rootDir>/dist/jimu-core/$1",
    '^jimu-theme/(.*)': '<rootDir>/dist/jimu-theme/$1',
    "^jimu-ui/(.*)": "<rootDir>/dist/jimu-ui/$1",
    '^jimu-icons/(.*)': '<rootDir>/jimu-icons/$1',
    "^jimu-for-builder/(.*)": "<rootDir>/dist/jimu-for-builder/$1",
    "^jimu-arcgis/(.*)": "<rootDir>/dist/jimu-arcgis/$1",
    "^jimu-layouts/(.*)": "<rootDir>/dist/jimu-layouts/$1",
    "^builder/(.*)": "<rootDir>/dist/builder/$1",
    "^site/(.*)": "<rootDir>/dist/site/$1",

    "^esri.*": "<rootDir>/__mocks__/esri-package-mock.js",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/file-mock.js",
    "\\.(css|scss)$": "<rootDir>/__mocks__/style-mock.js",
    "themes/(.*)\\variables.json": "<rootDir>/__mocks__/theme-mock.js",
    '^@arcgis/core/(.*)': '<rootDir>/__mocks__/esri-package-mock.js',
  },
  collectCoverage: false,
  silent: true,
  collectCoverageFrom: [
    "**/*.{ts,tsx}",
    "!**/*.d.ts",
    "!**/node_modules/**",
    "!**/woodpecker/**",
    "!**/dist*/**",
    "!**/arcgis-js-api/**",
    "!**/translations/**",
    "!tests/**",
    "!widgets/arcgis/**"
  ],
  coverageDirectory: "<rootDir>/dist-report/tests-coverage",
  coverageReporters: ["json", "html", "cobertura"],
  reporters: [
    "default",
    [
      "jest-junit",
      {
        outputDirectory: "dist-report",
        outputName: "ut-report.xml"
      }
    ]
  ],
  setupFiles: [
    './jimu-for-test/setup-jest.js'
  ]
}
```

**Comment by geospatialem** [comment]
Spike to reach out to ExB team to determine setup with Calcite and next steps.

**Comment by benelan** [comment]
@Matt-at-Hyland Can you try changing your `transformIgnorePatterns` to:

```js
  transformIgnorePatterns: [
    'node_modules/(?!(@esri/arcgis-rest-types|@arcgis/charts-spec|@esri/calcite-components(-react)?))'
  ],
```

I'm not sure if it will make a difference, but `@esri/calcite-components-react` is just React wrapper components for `@esri/calcite-components`, which may need to be transformed as well.

I think the regex above is correct, but just in case, this is a more explicit way of doing it:

```js
  transformIgnorePatterns: [
    'node_modules/(?!(@esri/arcgis-rest-types|@arcgis/charts-spec|@esri/calcite-components-react|@esri/calcite-components))'
  ],
```

**Comment by Matt-at-Hyland** [comment]
This made it work...thank you!
```
transformIgnorePatterns: [
    'node_modules/(?!(@esri/arcgis-rest-types|@arcgis/charts-spec|@esri/calcite-components(-react)?))'
  ],
```
