### ISSUE TITLE
CalciteTabNav throwing console.error on load

### ISSUE THREAD

**Issue by nikki-lea** [Esri/calcite-design-system#9057]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Console errors showing up on loading studio project

### Expected Behavior

No console errors should appear

### Reproduction Sample

Not reproducible outside studio

### Reproduction Steps

1. In studio, open a project and switch tabs
2. Click the logo in the top left to navigate back to the landing page
3. Open a project again
4. Error may show in the console

### Reproduction Version

2.7.1

### Relevant Info

```
TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at Array.eval (tab-nav.js:323:55)
    at consume (index.js:4130:21)
    at flush (index.js:4163:5) undefined
```
I confirm the error stops happening if I made the following changes:
1. Add an optional check on `tabTitleContainer` on lines 319 & 321 here - https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/tab-nav/tab-nav.tsx#L319
2. Check that `containerBounds` is defined in the if statements conditions on line 330 & 337 in the above file

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Enterprise

**Comment by nikki-lea** [comment]
Apologies for the delay @jcfranco, I met with you regarding this issue and mentioned that I would provide a test server in which the error could be reproduced - it took us a while for our version of calcite to get updated in main to where the error is now reproducible! The test server that you can use is https://etait.esri.com/portal/apps/knowledge-studio/landing, the error should show up on opening any existing project listed.

**Comment by jcfranco** [comment]
Belated thanks, @nikki-lea! 

This issue occurs because `tab-title`s [are activated](https://github.com/Esri/calcite-design-system/blob/2fcf11ee0567b48631cf7d5bb43d56344fffcaf7/packages/calcite-components/src/components/tab-title/tab-title.tsx#L446) during [initialization](https://github.com/Esri/calcite-design-system/blob/2fcf11ee0567b48631cf7d5bb43d56344fffcaf7/packages/calcite-components/src/components/tab-title/tab-title.tsx#L173-L175) and the `tab-nav` has not rendered before the [tab-scrolling logic takes place](https://github.com/Esri/calcite-design-system/blob/d570023ab447b6ba6694c38b611efae4db2cc0eb/packages/calcite-components/src/components/tab-nav/tab-nav.tsx#L254).

**Comment by jcfranco** [comment]
This might benefit from https://github.com/Esri/calcite-design-system/issues/10310, so I'd like to propose holding this off until that's landed.

@nikki-lea confirmed that the updated timeline should be fine.

**Comment by jcfranco** [comment]
@nikki-lea Is this still an issue with the latest version of `calcite-components`? I wasn't able to open a project following the [earlier steps](https://github.com/Esri/calcite-design-system/issues/9057#issuecomment-2108834874).

**Comment by nikki-lea** [comment]
@jcfranco, no longer reproducible - this issue can be closed :)

**Comment by geospatialem** [comment]
> Issue [#10310](https://github.com/Esri/calcite-design-system/issues/10310) has been closed, this issue is ready for re-evaluation.

The above is no longer reproducible as mentioned in https://github.com/Esri/calcite-design-system/issues/9057#issuecomment-4546299499 and https://github.com/Esri/calcite-design-system/issues/9057#issuecomment-4557265173. Closing the above out!
