### ISSUE TITLE
[action-menu, input-number] Restore unstable tests

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9784]
### Priority impact

p - high

### Test type

E2E Test

### Which Component(s)

`calcite-action-menu`, `calcite-input-number`

### Unstable Tests

* ~`calcite-action-menu › should close menu if slotted action is clicked`~ https://github.com/Esri/calcite-design-system/pull/10921
* ` calcite-input-number › should stop increasing the value when pointer is moved away from the increment button`

### Test error, if applicable

```bash
@esri/calcite-components:test: FAIL src/components/action-menu/action-menu.e2e.ts (19.686 s)
@esri/calcite-components:test:   ● calcite-action-menu › should close menu if slotted action is clicked
@esri/calcite-components:test: 
@esri/calcite-components:test:     expect(received).toBe(expected) // Object.is equality
@esri/calcite-components:test: 
@esri/calcite-components:test:     Expected: false
@esri/calcite-components:test:     Received: true
@esri/calcite-components:test: 
@esri/calcite-components:test:       197 |     await page.waitForChanges();
@esri/calcite-components:test:       198 |
@esri/calcite-components:test:     > 199 |     expect(await actionMenu.getProperty("open")).toBe(false);
@esri/calcite-components:test:           |                                                  ^
@esri/calcite-components:test:       200 |
@esri/calcite-components:test:       201 |     const focusTargetSelector = `#triggerAction`;
@esri/calcite-components:test:       202 |     expect(await page.evaluate((selector) => document.activeElement.matches(selector), focusTargetSelector)).toBe(true);
@esri/calcite-components:test: 
@esri/calcite-components:test:       at Object.<anonymous> (src/components/action-menu/action-menu.e2e.ts:199:50)
@esri/calcite-components:test: 
@esri/calcite-components:test: FAIL src/components/input/input.e2e.ts (510.561 s)
@esri/calcite-components:test:   ● calcite-input › input type number increment/decrement functionality › should stop increasing the value when pointer is moved away from the increment button
@esri/calcite-components:test: 
@esri/calcite-components:test:     expect(received).toEqual(expected) // deep equality
@esri/calcite-components:test: 
@esri/calcite-components:test:     Expected: "20"
@esri/calcite-components:test:     Received: "21"
@esri/calcite-components:test: 
@esri/calcite-components:test:       702 |       await page.mouse.move(incrementButtonRect.x, 2 * incrementButtonRect.bottom);
@esri/calcite-components:test:       703 |       await page.waitForChanges();
@esri/calcite-components:test:     > 704 |       expect(await input.getProperty("value")).toEqual(value);
@esri/calcite-components:test:           |                                                ^
@esri/calcite-components:test:       705 |
@esri/calcite-components:test:       706 |       await page.mouse.up();
@esri/calcite-components:test:       707 |       await page.waitForChanges();
@esri/calcite-components:test: 
@esri/calcite-components:test:       at Object.<anonymous> (src/components/input/input.e2e.ts:704:48)
```

### PR skipped, if applicable

#9783

**Comment by jcfranco** [comment]
The remaining unstable test from this issue was addressed in https://github.com/Esri/calcite-design-system/pull/12355. Closing!
